version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: x64
install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\deps
  - cd C:\deps
  
  ############################################################################
  # Set boost variables
  ############################################################################
  #- "SET BOOST_ROOT=C:\\Libraries\\boost_1_60_0"
  #- "SET BOOST_LIBRARYDIR=C:\\"

  #- ls C:\Libraries\boost_1_60_0

  ############################################################################
  # Install YAML-cpp
  ############################################################################
  - set YAML-cpp_URL="https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.5.3.zip"
  - appveyor DownloadFile %YAML-cpp_URL% -FileName yaml-cpp-0.5.3.zip
  - 7z x yamp-cpp-0.5.3.zip -oC:\deps\yamp-cpp-0.5.3 > nul
  - set PATH=C:\deps\yamp-cpp-0.5.3;%PATH%
  - SET YAML-CPP_DIR=C:\deps\yamp-cpp-0.5.3
  
  ############################################################################
  # Install CGAL 4.8
  ############################################################################
  - set CGAL_URL="https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.8/CGAL-4.8.zip"
  - appveyor DownloadFile %CGAL_URL% -FileName CGAL-4.8.zip
  - 7z x CGAL-4.8.zip -oC:\deps\CGAL-4.8 > nul
  - set PATH=C:\deps\CGAL-4.8;%PATH%
  - set CGAL_DIR=C:\deps\CGAL-4.8
  
  ############################################################################
  # Install OSGeo4W
  ############################################################################
  - ps: (new-object net.webclient).DownloadFile('http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe', 'osgeo4w-setup-x86_64.exe')
  - osgeo4w-setup-x86_64.exe --quiet-mode --upgrade-also --delete-orphans --no-desktop --advanced  --root C:\OSGeo4w --packages msvcrt setup shell avce00 zlib iconv libxml2 cairo openssl curl expat fcgi ffmpeg fftw freexl fribidi libpng libjpeg libjpeg12 libtiff libgeotiff proj-hpgn proj-datumgrid proj geos libmysql sqlite3 hdf5 netcdf libpq xerces-c-vc10 hdf4 ogdi openjpeg spatialite gdal liblas liblas-devel laszip --site http://download.osgeo.org/osgeo4w
 
  #- SET OSGEO4W_ROOT=C:\OSGeo4W
  # ############################################################################
  # # Install GDAL 2.1.3
  # ############################################################################
  # - ps: mkdir C:\deps\gdal | out-null
  
  # - curl http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-2-1-3-mapserver-7-0-4-20170202.zip --output gdalbin.zip
  # - 7z x gdalbin.zip -oC:\deps\gdal
  # - curl http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-2-1-3-mapserver-7-0-4-20170202-libs.zip --output gdallibs.zip  
  # - 7z x gdallibs.zip -oC:\deps\gdal
  # - set PATH=C:\deps\gdal;C:\deps\gdal\bin;C:\deps\gdal\data;C:\deps\gdal\bin\gdal\apps;%PATH%
  # - set GDAL_DATA=C:\deps\gdal\bin\gdal-data
  
  - set
build:
  project: vs_build\3dfier.sln
  verbosity: minimal
# notifications:
# - provider: Email
  # to:
  # - t.j.f.commandeur@tudelft.nl
  # subject: Build new version of discretise-polygons
  # on_build_success: true
  # on_build_failure: true
  # on_build_status_changed: false