
input_polygons:
  - datasets: 
      - /Users/hugo/data/campus/partof.shp
    uniqueid: FACE_ID
    lifting: BLOCK-AVG

  
input_elevation:
  - /Users/hugo/data/campus/coverpartof.laz

output: 
  format: CityGML
  verticaltriangles: true

simplification:
  thininputpoints: 100

buildings:
  horizontal_floor: true
  triangulated: false

verbose: true