input_polygons:                                         # Group for 2D input polygons
  - datasets:                                           # List of data set with specific settings
      - /Users/elvis/data/campus/partof.shp             # Input file, can be full path or relative to the executable
    uniqueid: FACE_ID                                   # Unique identifier attribute within input file
    lifting: Building                                   # Class to which this input file will be mapped, class settings are defined in lifting_options
  - datasets:
      - /Users/elvis/data/campus/another.gml            # Definition for multiple files using the same parameters
      - /Users/elvis/data/campus/another2.gml           #
    uniqueid: fid
    lifting_per_layer:                                  # Settings for mapping class to the layers defined within the input files
      Gebouw: Building                                  # Layer to class linking, 'Layer name in file:Class'
      Terrein: Terrain
      Waterdeel: Water
  - datasets: 
      - /Users/elvis/data/bgt_overbruggingsdeel.sqlite
    uniqueid: gml_id
    lifting: Bridge/Overpass
    height_field: relatievehoogteligging                # Attribute containing relative height level, should be an integer where ground surface is 0
    handle_multiple_heights: true                       # Use the height_field | false; use only height_field with value 0 | true; use all heights
  
lifting_options:                                        # Group for class lifting options
  Building:                                             # Class definition for Building
    height_roof: percentile-90                          # Percentile of points within radius of building vertices for roof height lifting, building_radius_vertex_elevation is defined in options
    height_floor: percentile-10                         # Percentile of points within radius of building vertices for floor height lifting
    triangulate: true                                   # Triangulate building faces | false; create polygons | true; triangulate polygons
  Water:                                                # Class definition for Water
    height: percentile-10                               # Percentile of points within radius of water vertices for lifting, radius_vertex_elevation is defined in options
  Road:
    height: percentile-50
  Separation:
    height: percentile-80
  Bridge/Overpass:
    height: percentile-50
  Terrain:                                              # Class definition for Terrain
    simplification: 100                                 # Simplification factor for points added within terrain polygons, points are added random
    inner_buffer: 1.0                                   # Inner buffer in meters where no additional points will be added within the terrain polygon
  Forest:                                               # Class definition for Forest
    simplification: 10                                  # Simplification factor for points added within forest polygons, points are added random
    inner_buffer: 1.0                                   # Inner buffer in meters where no additional points will be added within the forest polygon

input_elevation:                                        # Group for point clouds
  - datasets:                                           # List of data set with specific settings
      # - /Users/elvis/data/top10nl/schie/ahn2_u.laz    # Definition for one or multiple LAS/LAZ files using the same parameters
      # - /Users/elvis/data/top10nl/schie/ahn2_g.laz    #
      - /Users/elvis/data/top10nl/schie/ahn3.laz        #
    omit_LAS_classes:                                   # Option to omit classes defined in the files
      - 1 # unclassified                                # ASPRS Standard Lidar Point Classes classification value
      - 6 # building
    thinning: 10                                        # Thinning factor for points, this is the amount of points skipped during read, a value of 10 would result in points 1, 11, 21, 31 beeing used

options:                                                # Global options
  building_radius_vertex_elevation: 3.0                 # Radius in meters used for point-vertex distance between 3D points and building polygons, radius_vertex_elevation used when not specified
  radius_vertex_elevation: 1.0                          # Radius in meters used for point-vertex distance between 3D points and polygons
  threshold_jump_edges: 0.25                            # Threshold in meters for stitching adjacent objects, when the height difference is larger then the threshold a vertical wall is created 
  stitching: true                                       # Adjust heights of polygons after stiching and add vertical wallss

output:                                                 # Group for writing options
  format: OBJ                                           # Output file format, OBJ, OBJ-NoID, OBJ-BUILDINGS, CSV-BUILDINGS, CityGML or Shapefile
  building_floor: false                                 # Write the floor of a building to create solids
  vertical_exaggeration: 3                              # Multiplication factor for the height values, sometimes wanted for visualisation purposes