
input_polygons:
  - datasets: 
      - /Users/hugo/data/campus/partof.shp
    uniqueid: FACE_ID
    lifting: BLOCK-AVG
  
  - datasets: 
      - /Users/hugo/data/campus/another.gml
      - /Users/hugo/data/campus/another2.gml
    uniqueid: fid
    layers:
      Gebouw: BLOCK-PERCENTILE95
      Terrain: TIN-ALL_POINTS
      Waterdeel: BOUNDARY3D
  
input_elevation:
  - /Users/hugo/data/temp/potato.laz
  - /Users/hugo/data/campus/coverpartof.laz
  - /Users/hugo/data/temp/*.las

output: 
  format: CityGML
  verticaltriangles: true

simplification:
  thininputpoints: 100

buildings:
  horizontal_floor: true
  triangulated: false

verbose: true
