
input_polygons:
  - datasets: 
      - /Users/hugo/data/campus/partof.shp
    uniqueid: FACE_ID
    lifting: BLOCK_MEDIAN
  
  - datasets: 
      - /Users/hugo/data/campus/another.gml
      - /Users/hugo/data/campus/another2.gml
    uniqueid: fid
    layers:
      Gebouw: BLOCK_AVG
      Terrain: TIN_ALL_POINTS
      Waterdeel: BOUNDARY_3D
  
input_elevation:
  - /Users/hugo/data/campus/coverpartof.laz
  - /Users/hugo/data/temp/*.laz
  - /Users/hugo/data/temp/*.las

output: 
  format: CityGML
  verticaltriangles: true

simplification:
  thininputpoints: 100

buildings:
  horizontal_floor: true
  triangulated: false

verbose: true