input_polygons:
  - datasets: 
      - /Users/elvis/data/campus/partof.shp
    uniqueid: FACE_ID
    lifting: Building
  - datasets: 
      - /Users/elvis/data/campus/another.gml
      - /Users/elvis/data/campus/another2.gml
    uniqueid: fid
    lifting_per_layer:
      Gebouw: Building
      Terrein: Terrain
      Waterdeel: Water
  - datasets: 
      - /Users/elvis/data/bgt_overbruggingsdeel.sqlite
    uniqueid: gml_id
    lifting: Bridge/Overpass
    height_field: relatievehoogteligging
    handle_multiple_heights: true
  
lifting_options: 
  Building:
    height_roof: percentile-95
    height_floor: percentile-10
    triangulate: true
  Water:
    height: percentile-10
  Road:
    height: percentile-50
  Separation:
    height: percentile-80
  Bridge/Overpass:
    height: percentile-50
  Terrain:
    simplification: 100
  Vegetation:
    simplification: 10

input_elevation:
  - datasets:
      # - /Users/elvis/data/top10nl/schie/ahn2_u.laz
      # - /Users/elvis/data/top10nl/schie/ahn2_g.laz
      - /Users/elvis/data/top10nl/schie/ahn3.laz
    omit_LAS_classes:
      - 1 # unclassified
      - 6 # building
    thinning: 10

options:
  building_radius_vertex_elevation: 3.0
  radius_vertex_elevation: 1.0
  threshold_jump_edges: 0.25

output: 
  format: OBJ # OBJ-NoID, OBJ-BUILDINGS, CityGML, CSV-BUILDINGS or Shapefile
  building_floor: false
  vertical_exaggeration: 3

buildings:
  horizontal_floor: true
  triangulated: false
